export const goods = [
    {
        id: crypto.randomUUID(),
        itemName: "Cardboard Boxes (Medium)",
        category: "Packaging",
        type: "Good",
        quantity: 800,
        unit: "boxes",
        minimumStock: 150,
        reorderPoint: 200,
        supplier: "PackPro",
        vendorLocation: "Warehouse B",
        unitCost: 1.2,
        totalCost: 960,
        status: "IN STOCK",
        lastUpdated: "2026-07-19",
        notes: "Used for shipping books",
    },
    {
        id: crypto.randomUUID(),
        itemName: "Bubble Wrap Rolls",
        category: "Packaging",
        type: "Good",
        quantity: 120,
        unit: "rolls",
        minimumStock: 30,
        reorderPoint: 40,
        supplier: "PackPro",
        vendorLocation: "Warehouse B",
        unitCost: 8.5,
        totalCost: 1020,
        status: "OUT STOCK",
        lastUpdated: "2026-07-19",
        notes: "For fragile book protection",
    },
    {
        id: crypto.randomUUID(),
        itemName: "Shipping Labels",
        category: "Shipping",
        type: "Good",
        quantity: 3000,
        unit: "labels",
        minimumStock: 500,
        reorderPoint: 700,
        supplier: "LabelHub",
        vendorLocation: "Office Storage",
        unitCost: 0.05,
        totalCost: 150,
        status: "IN STOCK",
        lastUpdated: "2026-07-19",
        notes: "Standard A6 labels",
    },
    {
        id: crypto.randomUUID(),
        itemName: "Pallets",
        category: "Storage",
        type: "Good",
        quantity: 60,
        unit: "pallets",
        minimumStock: 15,
        reorderPoint: 20,
        supplier: "LogisticsCo",
        vendorLocation: "Warehouse A",
        unitCost: 12,
        totalCost: 720,
        status: "AVAILABLE",
        lastUpdated: "2026-07-19",
        notes: "Wooden pallets for bulk book storage",
    },
    {
        id: crypto.randomUUID(),
        itemName: "Book Display Stands",
        category: "Display",
        type: "Good",
        quantity: 12,
        unit: "stands",
        minimumStock: 3,
        reorderPoint: 5,
        supplier: "DisplayCraft",
        vendorLocation: "Sales Department",
        unitCost: 45,
        totalCost: 540,
        status: "IN STOCK",
        lastUpdated: "2026-07-19",
        notes: "Used in book fairs and events",
    },
    {
        id: crypto.randomUUID(),
        itemName: "Promotional Posters",
        category: "Marketing",
        type: "Good",
        quantity: 200,
        unit: "posters",
        minimumStock: 30,
        reorderPoint: 50,
        supplier: "PrintMedia",
        vendorLocation: "Marketing Room",
        unitCost: 2.5,
        totalCost: 500,
        status: "IN STOCK",
        lastUpdated: "2026-07-19",
        notes: "For selected book launches",
    },
    {
        id: crypto.randomUUID(),
        itemName: "Bookmarks",
        category: "Marketing",
        type: "Good",
        quantity: 1500,
        unit: "pieces",
        minimumStock: 300,
        reorderPoint: 400,
        supplier: "PrintMedia",
        vendorLocation: "Marketing Room",
        unitCost: 0.15,
        totalCost: 225,
        status: "IN STOCK",
        lastUpdated: "2026-07-19",
        notes: "Branded with company logo",
    },
    {
        id: crypto.randomUUID(),
        itemName: "Returned Books Pallet",
        category: "Returns",
        type: "Good",
        quantity: 5,
        unit: "pallets",
        minimumStock: 1,
        reorderPoint: 2,
        supplier: "Internal",
        vendorLocation: "Returns Section",
        unitCost: 0,
        totalCost: 0,
        status: "LOW STOCK",
        lastUpdated: "2026-07-19",
        notes: "Awaiting processing",
    },
];