// inventorySalesData.js

export const sales = [
    {
        id: 1,
        title: "The Silent City",
        author: "Layla Hassan",
        isbn: "978-1-23456-789-0",
        format: "ebook",
        category: "Fiction",
        unitPrice: 7.99,
        currency: "USD",
        copiesSold: 430,
        revenue: 3437.7,
        stockLeft: 120,
        status: "active",
        lastSaleDate: "2026-07-20",
        salesGrowth: 12,
        alert: null,
    },
    {
        id: 2,
        title: "Modern Data Workflows",
        author: "Sam Hatem",
        isbn: "978-1-23456-789-1",
        format: "ebook",
        category: "Technology",
        unitPrice: 9.99,
        currency: "USD",
        copiesSold: 210,
        revenue: 2097.9,
        stockLeft: 80,
        status: "active",
        lastSaleDate: "2026-07-19",
        salesGrowth: 8,
        alert: null,
    },
    {
        id: 3,
        title: "Designing Stories",
        author: "Maya Nasser",
        isbn: "978-1-23456-789-2",
        format: "print",
        category: "Design",
        unitPrice: 14.5,
        currency: "USD",
        copiesSold: 95,
        revenue: 1377.5,
        stockLeft: 12,
        status: "low-stock",
        lastSaleDate: "2026-07-18",
        salesGrowth: -3,
        alert: "Stock below reorder point",
    },
    {
        id: 4,
        title: "Publishing Basics",
        author: "Omar Khalil",
        isbn: "978-1-23456-789-3",
        format: "print",
        category: "Business",
        unitPrice: 12.0,
        currency: "USD",
        copiesSold: 40,
        revenue: 480,
        stockLeft: 0,
        status: "out-of-stock",
        lastSaleDate: "2026-07-10",
        salesGrowth: -15,
        alert: "Out of stock",
    },
    {
        id: 5,
        title: "Audio Editing Mastery",
        author: "Nina George",
        isbn: "978-1-23456-789-4",
        format: "audiobook",
        category: "Media",
        unitPrice: 11.99,
        currency: "USD",
        copiesSold: 150,
        revenue: 1798.5,
        stockLeft: null,
        status: "active",
        lastSaleDate: "2026-07-21",
        salesGrowth: 20,
        alert: null,
    },
    {
        id: 6,
        title: "Marketing for Authors",
        author: "Hassan Ali",
        isbn: "978-1-23456-789-5",
        format: "ebook",
        category: "Marketing",
        unitPrice: 8.5,
        currency: "USD",
        copiesSold: 0,
        revenue: 0,
        stockLeft: 50,
        status: "inactive",
        lastSaleDate: null,
        salesGrowth: 0,
        alert: "No sales yet",
    },
    {
        id: 7,
        title: "Novel Outline Toolkit",
        author: "Yara Saeed",
        isbn: "978-1-23456-789-6",
        format: "ebook",
        category: "Writing",
        unitPrice: 6.99,
        currency: "USD",
        copiesSold: 320,
        revenue: 2236.8,
        stockLeft: 200,
        status: "featured",
        lastSaleDate: "2026-07-15",
        salesGrowth: 25,
        alert: null,
    },
    {
        id: 8,
        title: "Intro to Poetry",
        author: "Rami Farid",
        isbn: "978-1-23456-789-7",
        format: "print",
        category: "Literature",
        unitPrice: 10.0,
        currency: "USD",
        copiesSold: 180,
        revenue: 1800,
        stockLeft: 5,
        status: "low-stock",
        lastSaleDate: "2026-07-17",
        salesGrowth: -5,
        alert: "Only a few copies left",
    },
    {
        id: 9,
        title: "Short Story Lab",
        author: "Laila Hassan",
        isbn: "978-1-23456-789-8",
        format: "ebook",
        category: "Fiction",
        unitPrice: 5.99,
        currency: "USD",
        copiesSold: 600,
        revenue: 3594,
        stockLeft: 300,
        status: "featured",
        lastSaleDate: "2026-07-21",
        salesGrowth: 30,
        alert: null,
    },
    {
        id: 10,
        title: "Freelance Writing Guide",
        author: "Tarek Nour",
        isbn: "978-1-23456-789-9",
        format: "ebook",
        category: "Business",
        unitPrice: 7.5,
        currency: "USD",
        copiesSold: 25,
        revenue: 187.5,
        stockLeft: 40,
        status: "discounted",
        lastSaleDate: "2026-07-12",
        salesGrowth: -10,
        alert: "On discount",
    },
    {
        id: 11,
        title: "World History 101",
        author: "Sara Mahmoud",
        isbn: "978-1-23456-790-0",
        format: "print",
        category: "Education",
        unitPrice: 15.0,
        currency: "USD",
        copiesSold: 120,
        revenue: 1800,
        stockLeft: 0,
        status: "out-of-stock",
        lastSaleDate: "2026-07-05",
        salesGrowth: -20,
        alert: "Out of stock",
    },
    {
        id: 12,
        title: "Science for Kids",
        author: "Omar Youssef",
        isbn: "978-1-23456-790-1",
        format: "audiobook",
        category: "Children",
        unitPrice: 9.99,
        currency: "USD",
        copiesSold: 200,
        revenue: 1998,
        stockLeft: null,
        status: "active",
        lastSaleDate: "2026-07-14",
        salesGrowth: 15,
        alert: null,
    },
    {
        id: 13,
        title: "Poetry for Beginners",
        author: "Nadia Samir",
        isbn: "978-1-23456-790-2",
        format: "ebook",
        category: "Literature",
        unitPrice: 4.99,
        currency: "USD",
        copiesSold: 80,
        revenue: 399.2,
        stockLeft: 60,
        status: "discontinued",
        lastSaleDate: "2026-06-20",
        salesGrowth: -50,
        alert: "Discontinued",
    },
    {
        id: 14,
        title: "Business Writing",
        author: "Khaled Ibrahim",
        isbn: "978-1-23456-790-3",
        format: "print",
        category: "Business",
        unitPrice: 13.5,
        currency: "USD",
        copiesSold: 160,
        revenue: 2160,
        stockLeft: 25,
        status: "active",
        lastSaleDate: "2026-07-16",
        salesGrowth: 5,
        alert: null,
    },
    {
        id: 15,
        title: "Travel Writing",
        author: "Mona Adel",
        isbn: "978-1-23456-790-4",
        format: "ebook",
        category: "Travel",
        unitPrice: 6.5,
        currency: "USD",
        copiesSold: 30,
        revenue: 195,
        stockLeft: 70,
        status: "inactive",
        lastSaleDate: "2026-06-25",
        salesGrowth: -8,
        alert: "No recent sales",
    },
    {
        id: 16,
        title: "Creative Journaling",
        author: "Huda Kamal",
        isbn: "978-1-23456-790-5",
        format: "print",
        category: "Self-Help",
        unitPrice: 11.0,
        currency: "USD",
        copiesSold: 220,
        revenue: 2420,
        stockLeft: 15,
        status: "low-stock",
        lastSaleDate: "2026-07-19",
        salesGrowth: 3,
        alert: "Stock below reorder point",
    },
    {
        id: 17,
        title: "Mystery Novels 101",
        author: "Bassam Taha",
        isbn: "978-1-23456-790-6",
        format: "ebook",
        category: "Fiction",
        unitPrice: 7.99,
        currency: "USD",
        copiesSold: 350,
        revenue: 2796.5,
        stockLeft: 180,
        status: "featured",
        lastSaleDate: "2026-07-20",
        salesGrowth: 18,
        alert: null,
    },
    {
        id: 18,
        title: "Cooking Basics",
        author: "Rania Fouad",
        isbn: "978-1-23456-790-7",
        format: "print",
        category: "Cooking",
        unitPrice: 16.0,
        currency: "USD",
        copiesSold: 90,
        revenue: 1440,
        stockLeft: 0,
        status: "out-of-stock",
        lastSaleDate: "2026-07-08",
        salesGrowth: -12,
        alert: "Out of stock",
    },
    {
        id: 19,
        title: "Healthy Living",
        author: "Iman Said",
        isbn: "978-1-23456-790-8",
        format: "audiobook",
        category: "Health",
        unitPrice: 10.5,
        currency: "USD",
        copiesSold: 170,
        revenue: 1785,
        stockLeft: null,
        status: "active",
        lastSaleDate: "2026-07-18",
        salesGrowth: 10,
        alert: null,
    },
    {
        id: 20,
        title: "Digital Marketing 101",
        author: "Wael Hassan",
        isbn: "978-1-23456-790-9",
        format: "ebook",
        category: "Marketing",
        unitPrice: 8.0,
        currency: "USD",
        copiesSold: 260,
        revenue: 2080,
        stockLeft: 100,
        status: "discounted",
        lastSaleDate: "2026-07-15",
        salesGrowth: 7,
        alert: "On discount",
    },
];