export const inventoryItems = [
  {
    id: crypto.randomUUID(),
    itemName: "A4 Paper",
    category: "Paper",
    type: "Material",
    quantity: 5000,
    unit: "sheets",
    minimumStock: 1000,
    reorderPoint: 1200,
    reorderQuantity: 3000,
    supplier: "PaperLine Co.",
    vendorLocation: "Bucharest Warehouse",
    unitCost: 0.12,
    totalCost: 600,
    status: "In stock",
    lastUpdated: "2026-07-14",
    notes: "Used for paperback printing",
  },
  {
    id: crypto.randomUUID(),
    itemName: "Glossy Cover Paper",
    category: "Cover Material",
    type: "Material",
    quantity: 1200,
    unit: "sheets",
    minimumStock: 500,
    reorderPoint: 600,
    reorderQuantity: 1500,
    supplier: "PrintSupplies Ltd.",
    vendorLocation: "Cluj Distribution Center",
    unitCost: 0.25,
    totalCost: 300,
    status: "In stock",
    lastUpdated: "2026-07-14",
    notes: "For hardcover and premium books",
  },
  {
    id: crypto.randomUUID(),
    itemName: "Black Ink",
    category: "Ink",
    type: "Material",
    quantity: 45,
    unit: "liters",
    minimumStock: 15,
    reorderPoint: 20,
    reorderQuantity: 30,
    supplier: "InkWorks",
    vendorLocation: "Main Printing Facility",
    unitCost: 18,
    totalCost: 810,
    status: "Low stock",
    lastUpdated: "2026-07-14",
    notes: "Standard text printing ink",
  },
  {
    id: crypto.randomUUID(),
    itemName: "Binding Glue",
    category: "Binding",
    type: "Material",
    quantity: 80,
    unit: "kg",
    minimumStock: 25,
    reorderPoint: 30,
    reorderQuantity: 50,
    supplier: "BindPro",
    vendorLocation: "Main Printing Facility",
    unitCost: 6.5,
    totalCost: 520,
    status: "In stock",
    lastUpdated: "2026-07-14",
    notes: "Used for perfect binding",
  },
  {
    id: crypto.randomUUID(),
    itemName: "SUN EATER",
    category: "Finished Book",
    type: "Book Stock",
    quantity: 200,
    unit: "copies",
    minimumStock: 50,
    reorderPoint: 75,
    reorderQuantity: 150,
    supplier: "Internal Production",
    vendorLocation: "Warehouse Section A",
    unitCost: 3.4,
    totalCost: 680,
    status: "In stock",
    lastUpdated: "2026-07-14",
    notes: "Ready for sale",
  },
  {
    id: crypto.randomUUID(),
    itemName: "MYSTIC LINES",
    category: "Ebook",
    type: "Digital Stock",
    quantity: 1,
    unit: "license",
    minimumStock: 1,
    reorderPoint: 1,
    reorderQuantity: 1,
    supplier: "Internal Production",
    vendorLocation: "Digital Library",
    unitCost: 0,
    totalCost: 0,
    status: "Available",
    lastUpdated: "2026-07-14",
    notes: "Digital version for online sale",
  },
  {
    id: crypto.randomUUID(),
    itemName: "Sample Pack",
    category: "Promotion",
    type: "Sample",
    quantity: 35,
    unit: "packs",
    minimumStock: 10,
    reorderPoint: 12,
    reorderQuantity: 25,
    supplier: "Marketing Team",
    vendorLocation: "Sales Department",
    unitCost: 1.2,
    totalCost: 42,
    status: "In stock",
    lastUpdated: "2026-07-14",
    notes: "Used for sales presentations",
  },
];