import book1Image from '../assets/images/book1.png'
import book3Image from '../assets/images/book3.png'
import { v4 as uuidv4 } from 'uuid';
export const books = [
    {
        title: 'SUN EATER',
        image: book1Image,
        number: 10,
        author: 'Megan campisi',
        date: '10/12/2022',
        pages: 222,
        edit: 'first',
        copies: 200,
        price: 300,
        type: 'Finished Books',
        state: 'translating',
        id: uuidv4()
    },
    {
        title: 'SUN EATER',
        image: book1Image,
        number: 10,
        author: 'Megan campisi',
        date: '10/12/2022',
        pages: 222,
        edit: 'first',
        copies: 200,
        price: 300,
        type: 'Finished Books',
        state: 'editing',
        id: uuidv4()
    }, {
        title: 'SUN EATER',
        image: book3Image,
        number: 10,
        author: 'Megan campisi',
        date: '10/12/2022',
        pages: 222,
        edit: 'first',
        copies: 200,
        price: 300,
        type: 'Books in-progress',
        state: 'checking',
        id: uuidv4()
    },
    {
        title: 'SUN EATER',
        image: book3Image,
        number: 10,
        author: 'Megan campisi',
        date: '10/12/2022',
        pages: 222,
        edit: 'first',
        copies: 200,
        price: 300,
        type: 'Books in-progress',
        state: 'translating',
        id: uuidv4()
    },
    {
        title: 'SUN EATER',
        image: book3Image,
        number: 10,
        author: 'Megan campisi',
        date: '10/12/2022',
        pages: 222,
        edit: 'first',
        copies: 200,
        price: 300,
        type: 'Books review needed',
        state: 'accepted',
        id: uuidv4()
    },
    {
        title: 'SUN EATER',
        image: book3Image,
        number: 10,
        author: 'Megan campisi',
        date: '10/12/2022',
        pages: 222,
        edit: 'first',
        copies: 200,
        price: 300,
        type: 'Books review needed',
        state: 'accepted',
        id: uuidv4()
    },
    {
        title: 'SUN EATER',
        image: book3Image,
        number: 10,
        author: 'Megan campisi',
        date: '10/12/2022',
        pages: 222,
        edit: 'first',
        copies: 200,
        price: 300,
        type: 'Ebooks',
        state: 'translating',
        id: uuidv4()
    },
    {
        title: 'SUN EATER',
        image: book3Image,
        number: 10,
        author: 'Megan campisi',
        date: '10/12/2022',
        pages: 222,
        edit: 'first',
        copies: 200,
        price: 300,
        type: 'Ebooks',
        state: 'accepted',
        id: uuidv4()
    },
    {
        title: 'SUN EATER',
        image: book3Image,
        number: 10,
        author: 'Megan campisi',
        date: '10/12/2022',
        pages: 222,
        edit: 'first',
        copies: 200,
        price: 300,
        type: 'Finished Books',
        state: 'accepted',
        id: uuidv4()
    },
    {
        title: 'SUN EATER',
        image: book3Image,
        number: 10,
        author: 'Megan campisi',
        date: '10/12/2022',
        pages: 222,
        edit: 'first',
        copies: 200,
        price: 300,
        type: 'Books in-progress',
        state: 'accepted',
        id: uuidv4()
    },
    {
        title: 'SUN EATER',
        image: book3Image,
        number: 10,
        author: 'Megan campisi',
        date: '10/12/2022',
        pages: 222,
        edit: 'first',
        copies: 200,
        price: 300,
        type: 'Books review needed',
        state: 'checking',
        id: uuidv4()
    },
    {
        title: 'SUN EATER',
        image: book3Image,
        number: 10,
        author: 'Megan campisi',
        date: '10/12/2022',
        pages: 222,
        edit: 'first',
        copies: 200,
        price: 300,
        type: 'Ebooks',
        state: 'checking',
        id: uuidv4()
    },
];