export const resources = [
    {
        id: 1,
        name: "PaperLine Co.",
        type: "Supplier",
        category: "Paper",
        status: "active",
        leadTimeDays: 5,
        capacityPercent: 70,
        onTimeRate: 96,
        activeShipments: 0,
        alert: null,
        contactEmail: "orders@paperline.com",
        contactPhone: "+40 21 123 4567",
    },
    {
        id: 2,
        name: "PrintFactory RO",
        type: "Production",
        category: "Printing",
        status: "delayed",
        leadTimeDays: 9,
        capacityPercent: 85,
        onTimeRate: 88,
        activeShipments: 2,
        alert: "Delivery delayed by 2 days",
        contactEmail: "production@printfactory.ro",
        contactPhone: "+40 21 555 7788",
    },
    {
        id: 3,
        name: "FastShip Logistics",
        type: "Logistics",
        category: "Shipping",
        status: "at-risk",
        leadTimeDays: 3,
        capacityPercent: 92,
        onTimeRate: 91,
        activeShipments: 6,
        alert: "High demand, possible delay",
        contactEmail: "support@fastship.com",
        contactPhone: "+40 31 222 3344",
    },
    {
        id: 4,
        name: "CloudBooks",
        type: "Digital",
        category: "Ebook Hosting",
        status: "down",
        leadTimeDays: 0,
        capacityPercent: 0,
        onTimeRate: 0,
        activeShipments: 0,
        alert: "Service currently unavailable",
        contactEmail: "help@cloudbooks.com",
        contactPhone: "+1 800 555 0100",
    },
];